# Generated by Django 5.1 on 2024-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_alter_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
